### Users create (signup)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "name": "test name",
  "email": "test1@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
}
